# The site that will be used to get the players' heads. Heads must be 8 pixels.
# Sites I recommend: mc-heads.net, crafthead.net, minotar.net, visage.surgeplay.com
heads-provider: 'https://mc-heads.net/avatar/%s/8'

resource-pack:
  # Should the plugin suggest to load the resource pack when the player joins the server?
  enabled: true

  # URL where the resource pack can be downloaded
  url: https://download.mc-packs.net/pack/dfb7102221ec6e923bf2e0d488bfa71a26186180.zip
  # SHA-1 hash
  hash: dfb7102221ec6e923bf2e0d488bfa71a26186180

  # Should the plugin sent messages?
  messaging: false
  # Should the plugin kick the player when they decline the resource pack or if the resource pack download fails?
  kick-player: true

  # The message to be sent if the resource pack is successfully loaded
  successfully-loaded: '§aResource pack successfully loaded!'
  # The message to be sent if the download fails.
  failed-download: '§cFailed to download the resource pack. Please, contact the staff!'
  # The message to be sent if the player declined the resource pack
  declined: '§cYou need to accept the resource pack to play on the server!'