name: HeadsAnywhere
main: ru.omashune.headsanywhere.HeadsAnywhere
version: {$project_version}
author: omashune
description: User players' heads anywhere!
website: https://github.com/omashune
api-version: 1.16
depend: [ PlaceholderAPI ]
softdepend: [ SkinsRestorer ]
libraries:
  - com.github.ben-manes.caffeine:caffeine:3.1.8